࿓❯ fix: Removed Docker information from README
nextcloud/nextcloudpi pull request #1851
Opened 2023-11-20 22:22 UTC by ZendaiOwl

Removed the Docker information from the README

Signed-off-by: Victor-ray, S <owl@zendai.net.eu.org>

2023-11-24 22:43 UTC, theCalcaholic commented
Thanks for the PR!

2023-11-24 22:46 UTC, theCalcaholic requested changes
Other than the mentioned minor change, this looks good to me

2023-11-24 22:46 UTC, theCalcaholic commented on README.md
> +<!-- This code also generates the NextcloudPi [Docker image][ncp-docker-hub], LXD container & VM, there is an install script for the latest stable Debian based system as well. -->
Can we reword this instead to

```diff
- This code also generates the NextcloudPi [Docker image][ncp-docker-hub], LXD container & VM, there is an install script for the latest stable Debian based system as well.
+ This code also generates the NextcloudPi LXD and LXC containers and there is an install script for the latest supported Debian based system as well.
```

2023-11-25 11:39 UTC, ZendaiOwl commented on README.md
> +<!-- This code also generates the NextcloudPi [Docker image][ncp-docker-hub], LXD container & VM, there is an install script for the latest stable Debian based system as well. -->
Of course, updating the PR now

2024-01-25 09:44 UTC, m-breitbach commented
Can we get this thing through to avoid more people from setting up their instances via Docker and than learn about the deprecation afterwards?

2024-02-01 09:03 UTC, ZendaiOwl commented
@theCalcaholic could you push this into master please? :)

2024-02-01 20:41 UTC, merged

2024-02-01 20:42 UTC, theCalcaholic commented
@ZendaiOwl Will do!